# TuinityPerPlayerViewDist
# by HeathFX (https://github.com/heathfx/TuinityPerPlayerViewDist)

#how often in seconds to check the permissions and locations of players
player-check-interval: 5

# - per-world settings - save server resources by not sending as many chunks to players that are
#   likely to be underground, not able to see very far anyways.
# - remove or comment out a world from this list to disable the feature for that world
# - remove or comment out the "worlds" section entirely to completely disable this feature
# - the worlds MUST MATCH your specific world names (not the dimension types). On PaperMC each
#   dimension has it's own folder, those folder names are the world names.
worlds:
    world:
        #restrict the view distance when player is below a certain y level
        reduce-view-distance-below-y: 60
        view-distance: 5
    world_nether:
        #restrict the view distance when player is below a certain y level
        reduce-view-distance-below-y: 30
        view-distance: 4

#print log message every time a player's view-disctance is changed by this plugin
verbose-logging: false