main: me.infectus.TuinityPerPlayerViewDist.Main
name: TuinityPerPlayerViewDist
version: 1.0.1
description: "Sets per-player unticked view-distance via permissions. Requres tuinity!"
author: infectus
api-version: 1.16